"""Solve the dissipative Yukawa-SYK equations and plot the relaxation rate."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


# Model parameters used for the relaxation-rate figure.
P = 2
J = 0.05
DELTA = 1.0
GAMMA_VALUES = np.array([0.15, 0.5, 1.0, 1.5, 2.0, 2.5])
KAPPA_VALUES = 0.2 * np.arange(1, 30)

# Numerical parameters for the real-time grid and fixed-point iteration.
N = 2**17
DT = 2.0
ETA = 1.0e-4
MIXING = 0.12
MAX_ITERATIONS = 600
TOLERANCE = 1.0e-5

OUTPUT_FILE = Path(__file__).with_name("Relaxation_rate_p_2.pdf")


@dataclass
class SDState:
    """Retarded and Keldysh propagators on the frequency grid."""

    fermion_retarded: np.ndarray
    fermion_keldysh: np.ndarray
    boson_retarded: np.ndarray
    boson_keldysh: np.ndarray


@dataclass
class SDSolution:
    """Converged propagators and fermionic retarded self-energy."""

    state: SDState
    fermion_self_energy_retarded: np.ndarray
    iterations: int
    residual: float


def make_frequency_grid(n: int, dt: float) -> tuple[np.ndarray, np.ndarray]:
    """Return centered time and angular-frequency grids with ``2*n`` points."""

    size = 2 * n
    time = (np.arange(size) - n) * dt
    frequency = 2.0 * np.pi * np.fft.fftshift(np.fft.fftfreq(size, d=dt))
    return time, frequency


def time_to_frequency(time: np.ndarray, values: np.ndarray) -> np.ndarray:
    """Compute ``F(w) = integral dt exp(+i*w*t) F(t)``."""

    dt = time[1] - time[0]
    return (
        dt
        * len(time)
        * np.fft.fftshift(np.fft.ifft(np.fft.ifftshift(values)))
    )


def frequency_to_time(frequency: np.ndarray, values: np.ndarray) -> np.ndarray:
    """Compute ``F(t) = integral dw/(2*pi) exp(-i*w*t) F(w)``."""

    dw = frequency[1] - frequency[0]
    return (
        dw
        / (2.0 * np.pi)
        * np.fft.fftshift(np.fft.fft(np.fft.ifftshift(values)))
    )


def values_at_negative_frequency(values: np.ndarray) -> np.ndarray:
    """Evaluate an array at ``-w`` on an even, centered FFT grid."""

    reflected = np.empty_like(values)
    reflected[0] = values[0]  # The unpaired Nyquist point.
    reflected[1:] = values[:0:-1]
    return reflected


def project_fermion_retarded(values: np.ndarray) -> np.ndarray:
    """Enforce the Majorana retarded symmetry ``F(w) = -F(-w)*``."""

    return 0.5 * (
        values - np.conjugate(values_at_negative_frequency(values))
    )


def project_boson_retarded(values: np.ndarray) -> np.ndarray:
    """Enforce the real-boson retarded symmetry ``F(w) = F(-w)*``."""

    return 0.5 * (
        values + np.conjugate(values_at_negative_frequency(values))
    )


def free_boson_inverse_retarded(
    frequency: np.ndarray,
    delta: float,
    kappa: float,
) -> np.ndarray:
    """Inverse retarded propagator of the lossy harmonic oscillator."""

    return (frequency + 0.5j * kappa) ** 2 - delta**2


def free_boson_inverse_keldysh(
    frequency: np.ndarray,
    delta: float,
    kappa: float,
) -> np.ndarray:
    """Inverse Keldysh kernel generated by zero-temperature boson loss."""

    return 1j * kappa / delta * (
        frequency**2 + delta**2 + 0.25 * kappa**2
    )


def free_state(
    frequency: np.ndarray,
    delta: float,
    kappa: float,
    eta: float,
) -> SDState:
    """Build the free infinite-temperature fermion and lossy-boson state."""

    fermion_retarded = 1.0 / (frequency + 1j * eta)
    fermion_keldysh = np.zeros_like(fermion_retarded)

    boson_retarded = 1.0 / free_boson_inverse_retarded(
        frequency, delta, kappa
    )
    boson_advanced = np.conjugate(boson_retarded)
    boson_keldysh = (
        -boson_retarded
        * free_boson_inverse_keldysh(frequency, delta, kappa)
        * boson_advanced
    )
    return SDState(
        fermion_retarded,
        fermion_keldysh,
        boson_retarded,
        boson_keldysh,
    )


def greater_and_lesser(
    retarded: np.ndarray,
    keldysh: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Convert retarded/advanced/Keldysh components to greater and lesser."""

    advanced = np.conjugate(retarded)
    greater = 0.5 * (keldysh + retarded - advanced)
    lesser = 0.5 * (keldysh - retarded + advanced)
    return greater, lesser


def sd_update(
    state: SDState,
    time: np.ndarray,
    frequency: np.ndarray,
    *,
    gamma: float,
    kappa: float,
    coupling: float,
    delta: float,
    interaction_order: int,
    eta: float,
) -> tuple[SDState, np.ndarray]:
    """Apply one full Schwinger-Dyson update in the R/A/K basis."""

    fermion_greater_w, fermion_lesser_w = greater_and_lesser(
        state.fermion_retarded, state.fermion_keldysh
    )
    boson_greater_w, boson_lesser_w = greater_and_lesser(
        state.boson_retarded, state.boson_keldysh
    )

    fermion_greater_t = frequency_to_time(frequency, fermion_greater_w)
    fermion_lesser_t = frequency_to_time(frequency, fermion_lesser_w)
    boson_greater_t = frequency_to_time(frequency, boson_greater_w)
    boson_lesser_t = frequency_to_time(frequency, boson_lesser_w)

    fermion_prefactor = (
        1j ** (interaction_order - 1)
        * 2.0
        * delta
        * gamma
        * coupling**2
    )
    boson_prefactor = (
        -(1j ** (interaction_order + 1))
        * 2.0
        * delta
        * coupling**2
        / interaction_order
    )

    sigma_greater_t = (
        fermion_prefactor
        * boson_greater_t
        * fermion_greater_t ** (interaction_order - 1)
    )
    sigma_lesser_t = (
        fermion_prefactor
        * boson_lesser_t
        * fermion_lesser_t ** (interaction_order - 1)
    )
    pi_greater_t = boson_prefactor * fermion_greater_t**interaction_order
    pi_lesser_t = boson_prefactor * fermion_lesser_t**interaction_order

    theta = np.heaviside(time, 0.5)
    sigma_retarded = time_to_frequency(
        time, theta * (sigma_greater_t - sigma_lesser_t)
    )
    sigma_keldysh = time_to_frequency(
        time, sigma_greater_t + sigma_lesser_t
    )
    pi_retarded = time_to_frequency(
        time, theta * (pi_greater_t - pi_lesser_t)
    )
    pi_keldysh = time_to_frequency(time, pi_greater_t + pi_lesser_t)

    # These exact symmetries suppress small discretization errors in the FFTs.
    sigma_retarded = project_fermion_retarded(sigma_retarded)
    pi_retarded = project_boson_retarded(pi_retarded)

    fermion_retarded = 1.0 / (
        frequency + 1j * eta - sigma_retarded
    )
    fermion_advanced = np.conjugate(fermion_retarded)
    boson_retarded = 1.0 / (
        free_boson_inverse_retarded(frequency, delta, kappa) - pi_retarded
    )
    boson_advanced = np.conjugate(boson_retarded)

    fermion_keldysh = (
        fermion_retarded * sigma_keldysh * fermion_advanced
    )
    boson_keldysh = (
        boson_retarded
        * (
            pi_keldysh
            - free_boson_inverse_keldysh(frequency, delta, kappa)
        )
        * boson_advanced
    )

    updated_state = SDState(
        fermion_retarded,
        fermion_keldysh,
        boson_retarded,
        boson_keldysh,
    )
    return updated_state, sigma_retarded


def relative_residual(new: np.ndarray, old: np.ndarray) -> float:
    """Return the largest update relative to the scale of the old array."""

    scale = max(1.0, float(np.max(np.abs(old))))
    return float(np.max(np.abs(new - old)) / scale)


def state_residual(new: SDState, old: SDState) -> float:
    """Return the largest relative residual among all four propagators."""

    return max(
        relative_residual(new.fermion_retarded, old.fermion_retarded),
        relative_residual(new.fermion_keldysh, old.fermion_keldysh),
        relative_residual(new.boson_retarded, old.boson_retarded),
        relative_residual(new.boson_keldysh, old.boson_keldysh),
    )


def mix_states(old: SDState, new: SDState, mixing: float) -> SDState:
    """Linearly mix the previous state with the latest SD update."""

    def mix(old_values: np.ndarray, new_values: np.ndarray) -> np.ndarray:
        return old_values + mixing * (new_values - old_values)

    return SDState(
        mix(old.fermion_retarded, new.fermion_retarded),
        mix(old.fermion_keldysh, new.fermion_keldysh),
        mix(old.boson_retarded, new.boson_retarded),
        mix(old.boson_keldysh, new.boson_keldysh),
    )


def solve_sd_equations(
    time: np.ndarray,
    frequency: np.ndarray,
    *,
    gamma: float,
    kappa: float,
    initial_state: SDState | None = None,
) -> SDSolution:
    """Iterate the SD equations until all propagators reach a fixed point."""

    state = (
        free_state(frequency, DELTA, kappa, ETA)
        if initial_state is None
        else initial_state
    )

    for iteration in range(1, MAX_ITERATIONS + 1):
        updated, _ = sd_update(
            state,
            time,
            frequency,
            gamma=gamma,
            kappa=kappa,
            coupling=J,
            delta=DELTA,
            interaction_order=P,
            eta=ETA,
        )
        residual = state_residual(updated, state)
        state = mix_states(state, updated, MIXING)
        if residual < TOLERANCE:
            break
    else:
        raise RuntimeError(
            f"SD iteration did not converge for gamma={gamma:g}, "
            f"kappa={kappa:g}; final residual={residual:.3e}"
        )

    # Recompute the self-energy from the returned, mixed state.
    _, sigma_retarded = sd_update(
        state,
        time,
        frequency,
        gamma=gamma,
        kappa=kappa,
        coupling=J,
        delta=DELTA,
        interaction_order=P,
        eta=ETA,
    )
    return SDSolution(state, sigma_retarded, iteration, residual)


def scan_relaxation_rates(
    time: np.ndarray,
    frequency: np.ndarray,
    gamma: float,
) -> np.ndarray:
    """Scan kappa from large to small, using each solution as the next seed."""

    rates = np.empty_like(KAPPA_VALUES)
    previous_state: SDState | None = None
    zero_index = int(np.argmin(np.abs(frequency)))

    for index in range(len(KAPPA_VALUES) - 1, -1, -1):
        kappa = float(KAPPA_VALUES[index])
        solution = solve_sd_equations(
            time,
            frequency,
            gamma=gamma,
            kappa=kappa,
            initial_state=previous_state,
        )
        rates[index] = -np.imag(
            solution.fermion_self_energy_retarded[zero_index]
        )
        previous_state = solution.state
        print(
            f"gamma={gamma:4.2f}, kappa={kappa:3.1f}: "
            f"Gamma={rates[index]:.7f} "
            f"({solution.iterations} iterations, "
            f"residual={solution.residual:.2e})"
        )

    return rates


def large_p_relaxation_rate(
    kappa: np.ndarray,
    gamma: float,
) -> np.ndarray:
    """Analytical relaxation rate used for the dashed comparison curves."""

    x = kappa / (2.0 * DELTA)
    return (
        J**2
        / (2 ** (P - 2) * P * DELTA)
        * np.sqrt(gamma + gamma**2 * P**2 * x**2)
        / (1.0 + x**2)
    )


def configure_plot_style() -> None:
    """Set a compact publication-style Matplotlib theme."""

    plt.rcParams.update(
        {
            "font.family": "serif",
            "mathtext.fontset": "cm",
            "font.size": 18,
            "axes.linewidth": 1.15,
            "xtick.direction": "in",
            "ytick.direction": "in",
            "xtick.top": True,
            "ytick.right": True,
            "xtick.major.size": 6,
            "ytick.major.size": 6,
            "xtick.minor.size": 3,
            "ytick.minor.size": 3,
        }
    )


def plot_relaxation_rates(rates_by_gamma: dict[float, np.ndarray]) -> None:
    """Plot numerical rates and their large-p comparison curves."""

    configure_plot_style()
    figure, axis = plt.subplots(figsize=(5.5, 5.2))
    colors = plt.cm.viridis(
        np.linspace(0.12, 0.88, len(GAMMA_VALUES))
    )[::-1]
    kappa_smooth = np.linspace(
        float(KAPPA_VALUES.min()), float(KAPPA_VALUES.max()), 400
    )
    rate_unit = J**2 / DELTA

    for line_index, (gamma, color) in enumerate(
        zip(GAMMA_VALUES[::-1], colors)
    ):
        axis.plot(
            KAPPA_VALUES / DELTA,
            rates_by_gamma[float(gamma)] / rate_unit,
            color=color,
            linewidth=1.35,
            marker="o",
            markersize=5.8,
            markerfacecolor="white",
            markeredgewidth=1.2,
            label=rf"$\gamma={gamma:g}$",
        )
        axis.plot(
            kappa_smooth / DELTA,
            large_p_relaxation_rate(kappa_smooth, float(gamma)) / rate_unit,
            color="0.2",
            linewidth=1.2,
            linestyle="--",
            label="Large-$p$" if line_index == 0 else "_nolegend_",
        )

    axis.set_xlabel(r"$\kappa/\Delta$")
    axis.set_ylabel(r"$\Gamma\;[J^2/\Delta]$")
    axis.set_xlim(-0.2, 6.2)
    axis.set_ylim(-0.04, 1.53)
    axis.minorticks_on()
    handles, labels = axis.get_legend_handles_labels()
    large_p_entry = [(h, label) for h, label in zip(handles, labels) if label == "Large-$p$"]
    gamma_entries = [(h, label) for h, label in zip(handles, labels) if label != "Large-$p$"]
    ordered_handles, ordered_labels = zip(*(gamma_entries + large_p_entry))
    axis.legend(ordered_handles, ordered_labels, fontsize=14, loc="upper right")
    figure.tight_layout()
    figure.savefig(OUTPUT_FILE)
    print(f"Saved figure to {OUTPUT_FILE}")
    plt.show()


def main() -> None:
    """Solve every parameter line and create the relaxation-rate figure."""

    time, frequency = make_frequency_grid(N, DT)
    rates_by_gamma = {
        float(gamma): scan_relaxation_rates(time, frequency, float(gamma))
        for gamma in GAMMA_VALUES
    }
    plot_relaxation_rates(rates_by_gamma)


if __name__ == "__main__":
    main()
